### ISSUE TITLE
Tipograph gets thrown off with multiple 2-digit years in a string (or something?)

### ISSUE THREAD

**Issue by handcoding** [pnevyk/tipograph#2]
Hi there, 

I think I may have come across a bug in Tipograph relating to smartening a string that has multiple 2-digit years inside the string (or something?). Here’s a test case:

`replace.all('I wasn\'t a particular fan of the music in the \'80s. And then she blurted, "I thought you said, \'I don\'t like \'80s music\'?"');`

Or if it might help, here’s that string in a more human-readable form:

> I wasn't a particular fan of the music in the '80s. And then she blurted, "I thought you said, 'I don't like '80s music\'?"

Here’s the result:

> I wasn’t a particular fan of the music in the ‘80s. And then she blurted, “I thought you said, ’I don’t like ‘80s music’?”

And here’s the result that I’d expect:

> I wasn’t a particular fan of the music in the ’80s. And then she blurted, “I thought you said, ‘I don’t like ’80s music’?”

If you happen to be viewing this issue on GitHub.com, you might be stuck seeing this in San Francisco, which happens to have nearly identical left-single-quote and right-single-quote characters. So if it might help, here’s a screenshot of those test cases but with Helvetica:

<img width="676" alt="tipograph - test case" src="https://cloud.githubusercontent.com/assets/118319/26524748/2335c4e0-4303-11e7-89cc-4f4f0c8aa0a8.png">

**Comment by pnevyk** [comment]
Thank you for your bug report and nice description. I added a test case with your sentence and one rule to handle two digit years. I can imagine that there are other inputs where my stupid Regex-based solution fails, in that case, feel free to create another issue.
