### ISSUE TITLE
Fix typo in README.md

### ISSUE THREAD

**Issue by mhulse** [pnevyk/tipograph#5]
As pointed out here:

https://github.com/pnevyk/tipograph/issues/4#issuecomment-404240991

There’s a small typo in the readme:

https://github.com/pnevyk/tipograph/blob/e79850ff6fa3733331d7ea4ed7501a836e09415b/README.md#installation

In process of making PR now.

**Comment by mhulse** [comment]
Oh, also, you’ve probably already seen this, but:

```bash
found 17 vulnerabilities (7 low, 9 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

I could fix those for you, but I’m less familular with the inner-workings of your code and the tests you have setup, etc. 

My guess is that `npm audit fix` would not introduce any regressions, but … 🤷‍♂️

**Comment by pnevyk** [comment]
I solved both `node-zopfli` (it was an optional dependency of `rollup-plugin-gzip` in older versions) and vulnerabilities problems right after you forked the repo :) Right now, it should be fine. But thanks for the info, I could missed that. And also thanks for the typo fix.

**Comment by mhulse** [comment]
Awesome! Thanks @pnevyk! Have a great rest of your day.

Cheers!
